// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZenlessZoneZeroWiki.Data;

#nullable disable

namespace ZenlessZoneZeroWiki.Migrations
{
    [DbContext(typeof(ZenlessZoneZeroContext))]
    [Migration("20250506014131_AddPurchaseHistory")]
    partial class AddPurchaseHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CharacterID"));

                    b.Property<int>("AllowedWeaponType")
                        .HasColumnType("int");

                    b.Property<int>("Attack")
                        .HasColumnType("int");

                    b.Property<int?>("CharacterType")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Element")
                        .HasColumnType("int");

                    b.Property<string>("FactionimageUrllink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrllink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("SignatureWeaponId")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeUrllink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("faction")
                        .HasColumnType("int");

                    b.HasKey("CharacterID");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.Favourite", b =>
                {
                    b.Property<int>("FavouriteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FavouriteID"));

                    b.Property<int?>("CharacterID")
                        .HasColumnType("int");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("TimeModified")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("WeaponID")
                        .HasColumnType("int");

                    b.HasKey("FavouriteID");

                    b.HasIndex("CharacterID");

                    b.HasIndex("FirebaseUid");

                    b.HasIndex("WeaponID");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("PurchaseHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PurchaseHistoryId"));

                    b.Property<string>("ImageUrllink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserFirebaseUid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PurchaseHistoryId");

                    b.ToTable("PurchaseHistories");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.ShoppingCart", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<string>("UserFirebaseUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("UserFirebaseUid")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShoppingCartItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.User", b =>
                {
                    b.Property<string>("FirebaseUid")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ApiKeyCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("FirebaseUid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WeaponID"));

                    b.Property<int>("AttackDMG")
                        .HasColumnType("int");

                    b.Property<int>("Defence")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrllink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("WeaponID");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.Favourite", b =>
                {
                    b.HasOne("ZenlessZoneZeroWiki.Models.Character", "Character")
                        .WithMany("Favourites")
                        .HasForeignKey("CharacterID");

                    b.HasOne("ZenlessZoneZeroWiki.Models.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("FirebaseUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZenlessZoneZeroWiki.Models.Weapon", "Weapon")
                        .WithMany("Favourites")
                        .HasForeignKey("WeaponID");

                    b.Navigation("Character");

                    b.Navigation("User");

                    b.Navigation("Weapon");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.ShoppingCart", b =>
                {
                    b.HasOne("ZenlessZoneZeroWiki.Models.User", "User")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("ZenlessZoneZeroWiki.Models.ShoppingCart", "UserFirebaseUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("ZenlessZoneZeroWiki.Models.ShoppingCart", "ShoppingCart")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.Character", b =>
                {
                    b.Navigation("Favourites");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.User", b =>
                {
                    b.Navigation("Favourites");

                    b.Navigation("ShoppingCart")
                        .IsRequired();
                });

            modelBuilder.Entity("ZenlessZoneZeroWiki.Models.Weapon", b =>
                {
                    b.Navigation("Favourites");
                });
#pragma warning restore 612, 618
        }
    }
}
