version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: zenless-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ZenlessZoneZeroDB
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: admin
    depends_on:
      - mysql

volumes:
  mysqldata:
